const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// Schema for individual Q&A items within a test
const TestItemSchema = new Schema({
    question_id: { type: String, required: true }, // generated by LLM or simple index
    question_text: { type: String, required: true },

    // User's input (Text for writing/reading, or transcript for speaking)
    user_answer: { type: String, default: null },

    // Optional: If the LLM provides choices (for reading/placement)
    options: [String],

    order: { type: Number, default: 0 }
}, { _id: false });

const TestSchema = new Schema({
    user_id: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    language_code: { type: String, required: true },
    language_level: { type: String, required: true },
    type: {
        type: String,
        enum: ['placement', 'reading', 'writing', 'speaking'],
        required: true
    },
    date_taken: { type: Date, default: Date.now },

    // STATUS: To track if the user submitted answers yet
    status: {
        type: String,
        enum: ['generated', 'submitted', 'graded'],
        default: 'generated'
    },

    content: [TestItemSchema],

    score: { type: Number, min: 0, max: 100, default: 0 },
    result_level: {
        type: String,
        enum: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'Pending'], // Added 'Pending'
        default: 'Pending'
    },
    details: { type: Map, of: String }
});

module.exports = mongoose.model('Test', TestSchema);